[[constraint]]
  name = "github.com/armon/go-radix"
  version = "1.0.0"

[[constraint]]
  name = "github.com/oschwald/geoip2-golang"
  version = "1.2.1"

[[constraint]]
  name = "github.com/oschwald/maxminddb-golang"
  version = "1.3.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/mcuadros/go-syslog.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
